In [1]:
import sys
print("Python Version:")
print(sys.version)
print("\nPython Executable Path:")
print(sys.executable)

Python Version:
3.9.23 (main, Jun  5 2025, 13:25:08) [MSC v.1929 64 bit (AMD64)]

Python Executable Path:
c:\Users\User\anaconda3\envs\tf210\python.exe


In [2]:
import tensorflow as tf

print("TensorFlow Version:", tf.__version__)
print("Num GPUs Available:", len(tf.config.list_physical_devices('GPU')))

# testing GPU availability and performing a simple operation
if tf.test.is_gpu_available():
    print("GPU is available.")
    with tf.device('/GPU:0'):
        a = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
        b = tf.constant([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])
        c = tf.matmul(a, b)
        print("Matrix multiplication on GPU:")
        print(c)
else:
    print("GPU is not available.")

TensorFlow Version: 2.10.0
Num GPUs Available: 1
Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
GPU is available.
Matrix multiplication on GPU:
tf.Tensor(
[[22. 28.]
 [49. 64.]], shape=(2, 2), dtype=float32)


In [3]:
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from tensorflow.keras.preprocessing.image import ImageDataGenerator

In [4]:
#load MNIST dataset
(x_train, y_train), (x_test, y_test) = mnist.load_data()

y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [5]:
x_train = x_train.reshape((x_train.shape[0], 28, 28, 1)).astype('float32') / 255
x_test = x_test.reshape((x_test.shape[0], 28, 28, 1)).astype('float32') / 255

x_train.shape

(60000, 28, 28, 1)

In [6]:
y_train = to_categorical(y_train, 10)
y_test = to_categorical(y_test, 10)

y_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], dtype=float32)

In [7]:
datagen = ImageDataGenerator(
    rotation_range=10, 
    width_shift_range=0.1,
    height_shift_range=0.1
)
datagen.fit(x_train)

In [ ]:
# 4. build simple CNN model
model = Sequential([
    Conv2D(32, (3,3), activation="relu", input_shape=(28,28,1)),
    MaxPooling2D(pool_size=(2,2)),

    Conv2D(64, (3,3), activation="relu"),
    MaxPooling2D(pool_size=(2,2)),

    Flatten(),
    Dense(128, activation="relu"),
    Dropout(0.5),  
    Dense(10, activation="softmax")
])

In [ ]:
# 5. compile the model
model.compile(
    loss="categorical_crossentropy",
    optimizer="adam",
    metrics=["accuracy"]
)

In [10]:
# 6. training the model
history = model.fit(
    datagen.flow(x_train, y_train, batch_size=64),
    epochs=10,
    validation_data=(x_test, y_test)
)

Epoch 1/10
938/938 [==============================] - 27s 13ms/step - loss: 0.4389 - accuracy: 0.8588 - val_loss: 0.0500 - val_accuracy: 0.9844
Epoch 2/10
938/938 [==============================] - 12s 13ms/step - loss: 0.1741 - accuracy: 0.9478 - val_loss: 0.0337 - val_accuracy: 0.9867
Epoch 3/10
938/938 [==============================] - 12s 13ms/step - loss: 0.1321 - accuracy: 0.9611 - val_loss: 0.0270 - val_accuracy: 0.9898
Epoch 4/10
938/938 [==============================] - 12s 13ms/step - loss: 0.1093 - accuracy: 0.9679 - val_loss: 0.0334 - val_accuracy: 0.9889
Epoch 5/10
938/938 [==============================] - 12s 13ms/step - loss: 0.0961 - accuracy: 0.9714 - val_loss: 0.0249 - val_accuracy: 0.9919
Epoch 6/10
938/938 [==============================] - 12s 13ms/step - loss: 0.0868 - accuracy: 0.9743 - val_loss: 0.0238 - val_accuracy: 0.9916
Epoch 7/10
938/938 [==============================] - 12s 13ms/step - loss: 0.0791 - accuracy: 0.9768 - val_loss: 0.0221 - val_accuracy:

In [12]:
# 7. evaluate the model
test_loss, test_acc = model.evaluate(x_test, y_test, verbose=0)
print("testing accuracy:", test_acc)

testing accuracy: 0.9936000108718872
